version: "3"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf