### Get weather
GET http://localhost:8080/api/v1/weather?userToken=123

### Get crop data
GET http://localhost:8080/api/v1/crop?userToken=123

### Get irrigation data
GET http://localhost:8080/api/v1/irrigation?userToken=123

### Create a new user
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "lat": 50.0,
  "lng": 19.0,
  "cropId": "4a2b1c46-f0af-4579-a002-ed5c0a096393",
  "cultivationArea": 1.5
}

### Get all crops
GET http://localhost:8080/api/v1/crop/all